// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTYogrQXT0-fEFJgX2eG8e1hYFgeMKLs',
    appId: '1:901043048658:web:52d29cdf8f95f0fecd5d0b',
    messagingSenderId: '901043048658',
    projectId: 'truelancerclone',
    authDomain: 'truelancerclone.firebaseapp.com',
    storageBucket: 'truelancerclone.appspot.com',
    measurementId: 'G-FGZSDG3RCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjEGemleY7GzbSjkliX-9inyDvuXxJdLw',
    appId: '1:901043048658:android:4a29a58d0b711180cd5d0b',
    messagingSenderId: '901043048658',
    projectId: 'truelancerclone',
    storageBucket: 'truelancerclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0NEDv1RF-pmGt0w1PxJYD4E31m66B4Q',
    appId: '1:901043048658:ios:687983cb1fc9cb56cd5d0b',
    messagingSenderId: '901043048658',
    projectId: 'truelancerclone',
    storageBucket: 'truelancerclone.appspot.com',
    iosClientId: '901043048658-gsa8hbn20v4q6gvadccj3knf3tpfb89q.apps.googleusercontent.com',
    iosBundleId: 'com.example.truelancerClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd0NEDv1RF-pmGt0w1PxJYD4E31m66B4Q',
    appId: '1:901043048658:ios:687983cb1fc9cb56cd5d0b',
    messagingSenderId: '901043048658',
    projectId: 'truelancerclone',
    storageBucket: 'truelancerclone.appspot.com',
    iosClientId: '901043048658-gsa8hbn20v4q6gvadccj3knf3tpfb89q.apps.googleusercontent.com',
    iosBundleId: 'com.example.truelancerClone',
  );
}
